apiVersion: v1
kind: Service
metadata:
  name: advisorrest-svc
  namespace: packapp05
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 85
    targetPort: 8080
    protocol: TCP
  selector:
    app: advisorrest

