apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerbank-deployment
  namespace: packapp05
spec:
  selector:
    matchLabels:
      app: containerbank
  replicas: 2
  template:
    metadata:
      labels:
        app: containerbank
    spec:
      containers:
      - name: containerbank
        image: registry.hackathon-container.com/packapp05/containerbank05:1.3
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: registry
